# Generated by Django 4.1.1 on 2022-09-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("breve_descricao", models.TextField()),
                ("ingredientes", models.TextField()),
                ("modo_de_preparo", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=18)),
                ("imagens", models.ImageField(blank=True, upload_to="")),
            ],
        ),
    ]
