# Generated by Django 4.1.1 on 2022-09-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita", old_name="imagens", new_name="link_imagens",
        ),
    ]
