# Generated by Django 4.1.1 on 2022-09-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita", old_name="breve_descricao", new_name="decricao",
        ),
    ]
