# Generated by Django 4.1.1 on 2022-09-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0002_rename_breve_descricao_receita_decricao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita", old_name="decricao", new_name="breve_descricao",
        ),
    ]
