# Generated by Django 4.1.1 on 2022-09-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0002_rename_imagens_receita_link_imagens"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita",
            old_name="breve_descrica0",
            new_name="breve_descricao",
        ),
    ]
