# Generated by Django 4.1.1 on 2022-09-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0003_rename_breve_descrica0_receita_breve_descricao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita", old_name="link_imagens", new_name="link_do_video",
        ),
        migrations.RemoveField(model_name="receita", name="ingredientes",),
        migrations.RemoveField(model_name="receita", name="modo_de_preparo",),
        migrations.RemoveField(model_name="receita", name="preco",),
    ]
